<?php 
    $conexio=array(
        "servidor"=>"127.0.0.1",
        #"port"=>"3306",
        #"host"=>"localhost",
        "bd"=>"Base_projecte", 
        "usuario"=>"root",
        "contrasenya"=>"");
?>