-- MySQL Script generated by MySQL Workbench
-- Tue Nov 27 20:20:16 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema base de datos
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Base_projecte
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Base_projecte
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Base_projecte` DEFAULT CHARACTER SET latin1 ;
USE `Base_projecte` ;

-- -----------------------------------------------------
-- Table `Base_projecte`.`Foros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Base_projecte`.`Foros` (
  `id_foro` VARCHAR(45) CHARACTER SET 'latin1' COLLATE 'latin1_bin' NOT NULL,
  `Titulo` CHAR(1) CHARACTER SET 'latin1' COLLATE 'latin1_bin' NOT NULL,
  `Descripcion` VARCHAR(45) CHARACTER SET 'latin1' COLLATE 'latin1_bin' NULL DEFAULT NULL,
  `Comentario` VARCHAR(100) CHARACTER SET 'latin1' COLLATE 'latin1_bin' NULL DEFAULT NULL,
  PRIMARY KEY (`id_foro`))
ENGINE = InnoDB
DEFAULT CHARSET=utf8;


-- -----------------------------------------------------
-- Table `Base_projecte`.`Juegos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Base_projecte`.`Juegos` (
  `idJuegos` INT(11) NOT NULL,
  `Nombre_juego` VARCHAR(45) CHARACTER SET 'latin1' COLLATE 'latin1_bin' NOT NULL,
  `descripcion` VARCHAR(45) CHARACTER SET 'latin1' COLLATE 'latin1_bin' NOT NULL,
  `ano` INT(4) NOT NULL,
  `consola` VARCHAR(45) CHARACTER SET 'latin1' COLLATE 'latin1_bin' NULL DEFAULT NULL,
  `precio` CHAR(45) CHARACTER SET 'latin1' COLLATE 'latin1_bin' NULL DEFAULT NULL,
  `en_venta` TINYINT(4) NULL DEFAULT NULL,
  `Article_idArticle` CHAR(3) CHARACTER SET 'latin1' COLLATE 'latin1_bin' NOT NULL,
  `Article_Series_y_peliculas_idSeries_peliculas` INT(11) NOT NULL,
  `Article_Personajes_idPersonajes` INT(11) NOT NULL,
  PRIMARY KEY (`idJuegos`, `Article_idArticle`, `Article_Series_y_peliculas_idSeries_peliculas`, `Article_Personajes_idPersonajes`))
ENGINE = InnoDB
DEFAULT CHARSET=utf8;

-- -----------------------------------------------------
-- Table `Base_projecte`.`Personajes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Base_projecte`.`Personajes` (
  `idPersonajes` INT(11) NOT NULL,
  `Nombre` VARCHAR(45) CHARACTER SET 'latin1' COLLATE 'latin1_bin' NOT NULL,
  `Descripcion` VARCHAR(45) CHARACTER SET 'latin1' COLLATE 'latin1_bin' NOT NULL,
  PRIMARY KEY (`idPersonajes`))
ENGINE = InnoDB
DEFAULT CHARSET=utf8;

-- -----------------------------------------------------
-- Table `Base_projecte`.`Usuaris`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Base_projecte`.`Usuaris` (
  `NOM_usuari` VARCHAR(10) NOT NULL,
  `Nom` VARCHAR(45) NOT NULL,
  `Apellidos` VARCHAR(45) NOT NULL,
  `Contrasenya` CHAR(16) NOT NULL,
  `Correu` CHAR(32) NOT NULL,
  `rol` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`NOM_usuari`))
ENGINE = InnoDB
DEFAULT CHARSET=utf8;
INSERT INTO Usuaris(NOM_usuari,Nom,Apellidos,Contrasenya,Correu,rol) VALUES
('admin','Jorge','Sendra','1234','hola@gmail.com','admin'),
('admindos','Sergi','Chismol','1234','hola@gmail.com','admindos'),
('user','usuari','resu','1234','user@gmail.com','user');

select * from Usuaris;

select rol from Usuaris where NOM_usuari = 'admin' AND Contrasenya = '1234';


-- -----------------------------------------------------
-- Table `Base_projecte`.`peliculas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Base_projecte`.`peliculas` (
  `idpeliculas` INT(11) NOT NULL,
  `titulo` VARCHAR(45) CHARACTER SET 'latin1' COLLATE 'latin1_bin' NULL DEFAULT NULL,
  `descripción` VARCHAR(45) CHARACTER SET 'latin1' COLLATE 'latin1_bin' NULL DEFAULT NULL,
  `Article_idArticle` CHAR(3) CHARACTER SET 'latin1' COLLATE 'latin1_bin' NOT NULL,
  `Article_Series_y_peliculas_idSeries_peliculas` INT(11) NOT NULL,
  `Article_Personajes_idPersonajes` INT(11) NOT NULL,
  PRIMARY KEY (`idpeliculas`))
ENGINE = InnoDB
DEFAULT CHARSET=utf8;
-- INSERT INTO peliculas(idpeliculas,titulo,descripción)
-- ('pelicula1','Los guerreros de plata',''),
-- ('pelicula2','Estalla el duelo',''),
-- ('pelicula3','La super batalla','')
-- ('pelicula4','La batalla de los dioses')
-- ('pelicula5','Dragon ball super: Broly')
-- -----------------------------------------------------
-- Table `Base_projecte`.`series`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Base_projecte`.`series` (
  `idseries` CHAR(11) NOT NULL,
  `nom` VARCHAR(45) CHARACTER SET 'latin1' COLLATE 'latin1_bin' NOT NULL,
  `descripcio` VARCHAR(70) CHARACTER SET 'latin1' COLLATE 'latin1_bin' NULL DEFAULT NULL,
  PRIMARY KEY (`idseries`))
ENGINE = InnoDB
DEFAULT CHARSET=utf8;
INSERT INTO series(idseries,nom,descripcio) VALUES
('serie1','Dragon ball','La aventura de Goku desde su niñez'),
('serie2','Dragon ball z','Son Goku experimenta las transformaciones del super guerrero'),
('serie3','Dragon ball super','Son Goku llega a rivalizar con los dioses'),
('serie4','Dragon ball GT','');

select * from series;

-- select idseries from series where serie2 =  AND  = '1234';
select nom, descripcio from series where idseries = 'serie1';

select nom, descripcio from series order by idseries desc ;

-- CREATE TABLE IF NOT EXISTS `imagenphp` (
-- `id` smallint(6) NOT NULL,
-- `ancho` smallint(6) NOT NULL,
-- `altura` smallint(6) NOT NULL,
-- `tipo` char(15) NOT NULL,
-- `imagen` mediumblob NOT NULL,
-- PRIMARY KEY (`id`)
-- ) 
-- ENGINE = InnoDB
-- DEFAULT CHARSET=utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


