-- MySQL Script generated by MySQL Workbench
-- Tue Nov 27 20:20:16 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema base de datos
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Base_projecte
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Base_projecte
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Base_projecte` DEFAULT CHARACTER SET latin1 ;
USE `Base_projecte` ;

-- -----------------------------------------------------
-- Table `Base_projecte`.`Foros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Base_projecte`.`Foros` (
  `id_foro` VARCHAR(45) CHARACTER SET 'latin1' COLLATE 'latin1_bin' NOT NULL,
  `Titulo` CHAR(1) CHARACTER SET 'latin1' COLLATE 'latin1_bin' NOT NULL,
  `Descripcion` VARCHAR(45) CHARACTER SET 'latin1' COLLATE 'latin1_bin' NULL DEFAULT NULL,
  `Comentario` VARCHAR(100) CHARACTER SET 'latin1' COLLATE 'latin1_bin' NULL DEFAULT NULL,
  PRIMARY KEY (`id_foro`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_bin;


-- -----------------------------------------------------
-- Table `Base_projecte`.`Juegos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Base_projecte`.`Juegos` (
  `idJuegos` INT(11) NOT NULL,
  `Nombre_juego` VARCHAR(45) CHARACTER SET 'latin1' COLLATE 'latin1_bin' NOT NULL,
  `descripcion` VARCHAR(45) CHARACTER SET 'latin1' COLLATE 'latin1_bin' NOT NULL,
  `ano` INT(4) NOT NULL,
  `consola` VARCHAR(45) CHARACTER SET 'latin1' COLLATE 'latin1_bin' NULL DEFAULT NULL,
  `precio` CHAR(45) CHARACTER SET 'latin1' COLLATE 'latin1_bin' NULL DEFAULT NULL,
  `en_venta` TINYINT(4) NULL DEFAULT NULL,
  `Article_idArticle` CHAR(3) CHARACTER SET 'latin1' COLLATE 'latin1_bin' NOT NULL,
  `Article_Series_y_peliculas_idSeries_peliculas` INT(11) NOT NULL,
  `Article_Personajes_idPersonajes` INT(11) NOT NULL,
  PRIMARY KEY (`idJuegos`, `Article_idArticle`, `Article_Series_y_peliculas_idSeries_peliculas`, `Article_Personajes_idPersonajes`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_bin;


-- -----------------------------------------------------
-- Table `Base_projecte`.`Personajes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Base_projecte`.`Personajes` (
  `idPersonajes` INT(11) NOT NULL,
  `Nombre` VARCHAR(45) CHARACTER SET 'latin1' COLLATE 'latin1_bin' NOT NULL,
  `Descripcion` VARCHAR(45) CHARACTER SET 'latin1' COLLATE 'latin1_bin' NOT NULL,
  PRIMARY KEY (`idPersonajes`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_bin;


-- -----------------------------------------------------
-- Table `Base_projecte`.`Usuaris`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Base_projecte`.`Usuaris` (
  `NOM_usuari` VARCHAR(10) NOT NULL,
  `Nom` VARCHAR(45) NOT NULL,
  `Apellidos` VARCHAR(45) NOT NULL,
  `Contraseña` CHAR(16) NOT NULL,
  `Correu` CHAR(32) NOT NULL,
  `rol` VARCHAR(45) NULL DEFAULT NULL
  PRIMARY KEY (`NOM_usuari`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Base_projecte`.`peliculas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Base_projecte`.`peliculas` (
  `idpeliculas` INT(11) NOT NULL,
  `titulo` VARCHAR(45) CHARACTER SET 'latin1' COLLATE 'latin1_bin' NULL DEFAULT NULL,
  `descripción` VARCHAR(45) CHARACTER SET 'latin1' COLLATE 'latin1_bin' NULL DEFAULT NULL,
  `Article_idArticle` CHAR(3) CHARACTER SET 'latin1' COLLATE 'latin1_bin' NOT NULL,
  `Article_Series_y_peliculas_idSeries_peliculas` INT(11) NOT NULL,
  `Article_Personajes_idPersonajes` INT(11) NOT NULL,
  PRIMARY KEY (`idpeliculas`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_bin;


-- -----------------------------------------------------
-- Table `Base_projecte`.`series`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Base_projecte`.`series` (
  `idseries` INT(11) NOT NULL,
  `nom` VARCHAR(45) CHARACTER SET 'latin1' COLLATE 'latin1_bin' NOT NULL,
  `descripcio` VARCHAR(45) CHARACTER SET 'latin1' COLLATE 'latin1_bin' NULL DEFAULT NULL,
  PRIMARY KEY (`idseries`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_bin;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
